### ISSUE TITLE
SVG issue: TypeError: Unsupported operand types: string * float

### ISSUE THREAD

**Issue by cargocultprogramming** [splitbrain/dokuwiki-plugin-dw2pdf#498]
On one of my namespaces I get the following error, seemingly while trying to parse an svg:

```
TypeError: Unsupported operand types: string * float
/var/www/dokuwiki/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Image/Svg.php(1477)
#0 /var/www/dokuwiki/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Image/Svg.php(3793): Mpdf\Image\Svg->svgStyle()
#1 [internal function]: Mpdf\Image\Svg->xml_svg2pdf_start()
#2 /var/www/dokuwiki/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Image/Svg.php(3130): xml_parse()
#3 /var/www/dokuwiki/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Image/ImageProcessor.php(274): Mpdf\Image\Svg->ImageSVG()
#4 /var/www/dokuwiki/lib/plugins/dw2pdf/DokuImageProcessorDecorator.php(26): Mpdf\Image\ImageProcessor->getImage()
#5 /var/www/dokuwiki/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Tag/Img.php(277): dokuwiki\plugin\dw2pdf\DokuImageProcessorDecorator->getImage()
#6 /var/www/dokuwiki/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Tag.php(243): Mpdf\Tag\Img->open()
#7 /var/www/dokuwiki/lib/plugins/dw2pdf/vendor/mpdf/mpdf/src/Mpdf.php(13752): Mpdf\Tag->OpenTag()
#8 /var/www/dokuwiki/lib/plugins/dw2pdf/action.php(540): Mpdf\Mpdf->WriteHTML()
#9 /var/www/dokuwiki/lib/plugins/dw2pdf/action.php(118): action_plugin_dw2pdf->generatePDF()
#10 /var/www/dokuwiki/inc/Extension/EventHandler.php(80): action_plugin_dw2pdf->convert()
#11 /var/www/dokuwiki/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
#12 /var/www/dokuwiki/inc/ActionRouter.php(80): dokuwiki\Extension\Event->advise_before()
#13 /var/www/dokuwiki/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction()
#14 /var/www/dokuwiki/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
#15 /var/www/dokuwiki/inc/actions.php(16): dokuwiki\ActionRouter::getInstance()
#16 /var/www/dokuwiki/doku.php(126): act_dispatch()
#17 {main}
```
Other namespaces are fine. I'm using Release 2023-04-04a "Jack Jackrum" with the latest version of dw2pdf from 2023-10-25.

**Comment by Klap-in** [comment]
Which syntax did you use in DokuWiki? Do you have an example svg which reproduce this?

**Comment by Klap-in** [comment]
I guess you use php8? Probably https://github.com/mpdf/mpdf/issues/1395
So if we upgrade the mPDF library we might fix this already.

**Comment by Klap-in** [comment]
Now a recent mPDF version is used in dw2pdf that supports 8.2+. As further feedback is missing I supposed this is now solved.
